export const DEVELOPER_LINK = 'https://7glyphs.com'
export const LINKEDIN_TOSS = 'https://nz.linkedin.com/in/toss-grumley'
export const LINKEDIN_COMPANY = 'https://www.linkedin.com/company/wolf-&-fox/'
export const FACEBOOK_LINK = 'https://www.facebook.com/wolfandfoxnz/'
// eslint-disable-next-line max-len
export const GOOGLE_REVIEWS_LINK = 'https://goo.gl/hFe9FE'
export const EVENTBRITE_REGISTER = 'https://www.eventbrite.co.nz/o/wolf-amp-fox-new-business-amp-growth-advisors-17152938921'
export const PHONE = '+64 9 390 5958'
export const EMAIL = 'enquiries@wolfandfox.co.nz'
export const ADDRESS = '7A/17 Albert Street, Auckland, 1010'
export const ADDRESS_SHORT = '7A/17 Albert St, Auckland, 1010'
export const GOOGLE_MAPS_API_KEY = 'AIzaSyB7G7jp5z6-mnn3buv9TbTNHhB-G99kums'
