export default {
  client_jess_img_full_sm: require('../assets/images/clients/clients_pics/full/jess.jpg'),
  client_jess_img_full_md: require('../assets/images/clients/clients_pics/full/jess@2x.jpg'),
  client_jess_img_full_lg: require('../assets/images/clients/clients_pics/full/jess@3x.jpg'),
  client_jess_img_cropped_sm: require('../assets/images/clients/clients_pics/cropped/jess.png'),
  client_jess_img_cropped_md: require('../assets/images/clients/clients_pics/cropped/jess@2x.png'),
  client_jess_img_cropped_lg: require('../assets/images/clients/clients_pics/cropped/jess@3x.png'),
  client_jess_logo_sm: require('../assets/images/clients/clients_logos/jess.png'),
  client_jess_logo_md: require('../assets/images/clients/clients_logos/jess@2x.png'),
  client_jess_logo_lg: require('../assets/images/clients/clients_logos/jess@3x.png'),

  client_boyd_img_full_sm: require('../assets/images/clients/clients_pics/full/boyd.jpg'),
  client_boyd_img_full_md: require('../assets/images/clients/clients_pics/full/boyd@2x.jpg'),
  client_boyd_img_full_lg: require('../assets/images/clients/clients_pics/full/boyd@3x.jpg'),
  client_boyd_img_cropped_sm: require('../assets/images/clients/clients_pics/cropped/boyd.jpg'),
  client_boyd_img_cropped_md: require('../assets/images/clients/clients_pics/cropped/boyd@2x.jpg'),
  client_boyd_img_cropped_lg: require('../assets/images/clients/clients_pics/cropped/boyd@3x.jpg'),
  client_boyd_logo_sm: require('../assets/images/clients/clients_logos/boyd-clinic.png'),
  client_boyd_logo_md: require('../assets/images/clients/clients_logos/boyd-clinic@2x.png'),
  client_boyd_logo_lg: require('../assets/images/clients/clients_logos/boyd-clinic@3x.png'),

  client_nick_img_full_sm: require('../assets/images/clients/clients_pics/full/nick.jpg'),
  client_nick_img_full_md: require('../assets/images/clients/clients_pics/full/nick@2x.jpg'),
  client_nick_img_full_lg: require('../assets/images/clients/clients_pics/full/nick@3x.jpg'),
  client_nick_img_cropped_sm: require('../assets/images/clients/clients_pics/cropped/nick.jpg'),
  client_nick_img_cropped_md: require('../assets/images/clients/clients_pics/cropped/nick@2x.jpg'),
  client_nick_img_cropped_lg: require('../assets/images/clients/clients_pics/cropped/nick@3x.jpg'),
  client_nick_logo_sm: require('../assets/images/clients/clients_logos/nick.png'),
  client_nick_logo_md: require('../assets/images/clients/clients_logos/nick@2x.png'),
  client_nick_logo_lg: require('../assets/images/clients/clients_logos/nick@3x.png'),

  client_kiara_img_full_sm: require('../assets/images/clients/clients_pics/full/revitalash.jpg'),
  client_kiara_img_full_md: require('../assets/images/clients/clients_pics/full/revitalash@2x.jpg'),
  client_kiara_img_full_lg: require('../assets/images/clients/clients_pics/full/revitalash@3x.jpg'),
  client_kiara_img_cropped_sm: require('../assets/images/clients/clients_pics/cropped/kiara.jpg'),
  client_kiara_img_cropped_md: require('../assets/images/clients/clients_pics/cropped/kiara@2x.jpg'),
  client_kiara_img_cropped_lg: require('../assets/images/clients/clients_pics/cropped/kiara@3x.jpg'),
  client_kiara_logo_sm: require('../assets/images/clients/clients_logos/revitalash.png'),
  client_kiara_logo_md: require('../assets/images/clients/clients_logos/revitalash@2x.png'),
  client_kiara_logo_lg: require('../assets/images/clients/clients_logos/revitalash@3x.png'),

  client_caliwoods_img_full_sm: require('../assets/images/clients/clients_pics/full/cali-woods.jpg'),
  client_caliwoods_img_full_md: require('../assets/images/clients/clients_pics/full/cali-woods@2x.jpg'),
  client_caliwoods_img_full_lg: require('../assets/images/clients/clients_pics/full/cali-woods@3x.jpg'),
  client_caliwoods_img_cropped_sm: require('../assets/images/clients/clients_pics/cropped/cali-woods.jpg'),
  client_caliwoods_img_cropped_md: require('../assets/images/clients/clients_pics/cropped/cali-woods@2x.jpg'),
  client_caliwoods_img_cropped_lg: require('../assets/images/clients/clients_pics/cropped/cali-woods@3x.jpg'),
  client_caliwoods_logo_sm: require('../assets/images/clients/clients_logos/caliwoods.png'),
  client_caliwoods_logo_md: require('../assets/images/clients/clients_logos/caliwoods@2x.png'),
  client_caliwoods_logo_lg: require('../assets/images/clients/clients_logos/caliwoods@3x.png'),

  client_rogue_img_full_sm: require('../assets/images/clients/clients_pics/full/rogue.jpg'),
  client_rogue_img_full_md: require('../assets/images/clients/clients_pics/full/rogue@2x.jpg'),
  client_rogue_img_full_lg: require('../assets/images/clients/clients_pics/full/rogue@3x.jpg'),
  client_rogue_img_cropped_sm: require('../assets/images/clients/clients_pics/cropped/rogue.jpg'),
  client_rogue_img_cropped_md: require('../assets/images/clients/clients_pics/cropped/rogue@2x.jpg'),
  client_rogue_img_cropped_lg: require('../assets/images/clients/clients_pics/cropped/rogue@3x.jpg'),
  client_rogue_logo_sm: require('../assets/images/clients/clients_logos/rogue.svg'),

  client_lno_img_full_sm: require('../assets/images/clients/clients_pics/full/lno.jpg'),
  client_lno_img_full_md: require('../assets/images/clients/clients_pics/full/lno@2x.jpg'),
  client_lno_img_full_lg: require('../assets/images/clients/clients_pics/full/lno@3x.jpg'),
  client_lno_img_cropped_sm: require('../assets/images/clients/clients_pics/cropped/lno.jpg'),
  client_lno_img_cropped_md: require('../assets/images/clients/clients_pics/cropped/lno@2x.jpg'),
  client_lno_img_cropped_lg: require('../assets/images/clients/clients_pics/cropped/lno@3x.jpg'),
  client_lno_logo_sm: require('../assets/images/clients/clients_logos/lno.png'),
  client_lno_logo_md: require('../assets/images/clients/clients_logos/lno@2x.png'),
  client_lno_logo_lg: require('../assets/images/clients/clients_logos/lno@3x.png'),

  client_manuka_img_full_sm: require('../assets/images/clients/clients_pics/full/manuka.jpg'),
  client_manuka_img_full_md: require('../assets/images/clients/clients_pics/full/manuka@2x.jpg'),
  client_manuka_img_full_lg: require('../assets/images/clients/clients_pics/full/manuka@3x.jpg'),
  client_manuka_img_cropped_sm: require('../assets/images/clients/clients_pics/cropped/manuka.jpg'),
  client_manuka_img_cropped_md: require('../assets/images/clients/clients_pics/cropped/manuka@2x.jpg'),
  client_manuka_img_cropped_lg: require('../assets/images/clients/clients_pics/cropped/manuka@3x.jpg'),
  client_manuka_logo_sm: require('../assets/images/clients/clients_logos/manuka.png'),
  client_manuka_logo_md: require('../assets/images/clients/clients_logos/manuka@2x.png'),
  client_manuka_logo_lg: require('../assets/images/clients/clients_logos/manuka@3x.png'),

  client_capelli_img_full_sm: require('../assets/images/clients/clients_pics/full/capelli.jpg'),
  client_capelli_img_full_md: require('../assets/images/clients/clients_pics/full/capelli@2x.jpg'),
  client_capelli_img_full_lg: require('../assets/images/clients/clients_pics/full/capelli@3x.jpg'),
  client_capelli_img_cropped_sm: require('../assets/images/clients/clients_pics/cropped/capelli.jpg'),
  client_capelli_img_cropped_md: require('../assets/images/clients/clients_pics/cropped/capelli@2x.jpg'),
  client_capelli_logo_sm: require('../assets/images/clients/clients_logos/capelli.png'),
  client_capelli_logo_md: require('../assets/images/clients/clients_logos/capelli@2x.png'),
  client_capelli_logo_lg: require('../assets/images/clients/clients_logos/capelli@3x.png'),

  client_lash_img_full_sm: require('../assets/images/clients/clients_pics/full/noir.jpg'),
  client_lash_img_full_md: require('../assets/images/clients/clients_pics/full/noir@2x.jpg'),
  client_lash_img_full_lg: require('../assets/images/clients/clients_pics/full/noir@3x.jpg'),
  client_lash_img_cropped_sm: require('../assets/images/clients/clients_pics/cropped/lash.jpg'),
  client_lash_img_cropped_md: require('../assets/images/clients/clients_pics/cropped/lash@2x.jpg'),
  client_lash_img_cropped_lg: require('../assets/images/clients/clients_pics/cropped/lash@3x.jpg'),
  client_lash_logo_sm: require('../assets/images/clients/clients_logos/lash-noir.png'),
  client_lash_logo_md: require('../assets/images/clients/clients_logos/lash-noir@2x.png'),
  client_lash_logo_lg: require('../assets/images/clients/clients_logos/lash-noir@3x.png'),

  client_little_img_full_sm: require('../assets/images/clients/clients_pics/full/little-mango.jpg'),
  client_little_img_full_md: require('../assets/images/clients/clients_pics/full/little-mango@2x.jpg'),
  client_little_img_full_lg: require('../assets/images/clients/clients_pics/full/little-mango@3x.jpg'),
  client_little_img_cropped_sm: require('../assets/images/clients/clients_pics/cropped/little.jpg'),
  client_little_img_cropped_md: require('../assets/images/clients/clients_pics/cropped/little@2x.jpg'),
  client_little_img_cropped_lg: require('../assets/images/clients/clients_pics/cropped/little@3x.jpg'),
  client_little_logo_sm: require('../assets/images/clients/clients_logos/little-mango.png'),
  client_little_logo_md: require('../assets/images/clients/clients_logos/little-mango@2x.png'),
  client_little_logo_lg: require('../assets/images/clients/clients_logos/little-mango@3x.png'),

  client_glyphs_img_full_sm: require('../assets/images/clients/clients_pics/full/glyphs.jpg'),
  client_glyphs_img_full_md: require('../assets/images/clients/clients_pics/full/glyphs@2x.jpg'),
  client_glyphs_img_full_lg: require('../assets/images/clients/clients_pics/full/glyphs@3x.jpg'),
  client_glyphs_img_cropped_sm: require('../assets/images/clients/clients_pics/cropped/7-glyphs.jpg'),
  client_glyphs_img_cropped_md: require('../assets/images/clients/clients_pics/cropped/7-glyphs@2x.jpg'),
  client_glyphs_logo_sm: require('../assets/images/clients/clients_logos/7-glyphs.svg'),

  client_urban_img_full_sm: require('../assets/images/clients/clients_pics/full/the-urban-physio.jpg'),
  client_urban_img_full_md: require('../assets/images/clients/clients_pics/full/the-urban-physio@2x.jpg'),
  client_urban_img_full_lg: require('../assets/images/clients/clients_pics/full/the-urban-physio@3x.jpg'),
  client_urban_img_cropped_sm: require('../assets/images/clients/clients_pics/cropped/urban.jpg'),
  client_urban_img_cropped_md: require('../assets/images/clients/clients_pics/cropped/urban@2x.jpg'),
  client_urban_img_cropped_lg: require('../assets/images/clients/clients_pics/cropped/urban@3x.jpg'),
  client_urban_logo_sm: require('../assets/images/clients/clients_logos/the-urban.png'),
  client_urban_logo_md: require('../assets/images/clients/clients_logos/the-urban@2x.png'),
  client_urban_logo_lg: require('../assets/images/clients/clients_logos/the-urban@3x.png'),

  client_free_img_full_sm: require('../assets/images/clients/clients_pics/full/free.jpg'),
  client_free_img_full_md: require('../assets/images/clients/clients_pics/full/free@2x.jpg'),
  client_free_img_full_lg: require('../assets/images/clients/clients_pics/full/free@3x.jpg'),
  client_free_img_cropped_sm: require('../assets/images/clients/clients_pics/cropped/free.jpg'),
  client_free_img_cropped_md: require('../assets/images/clients/clients_pics/cropped/free@2x.jpg'),
  client_free_img_cropped_lg: require('../assets/images/clients/clients_pics/cropped/free@3x.jpg'),
  client_free_logo_sm: require('../assets/images/clients/clients_logos/free-range.png'),
  client_free_logo_md: require('../assets/images/clients/clients_logos/free-range@2x.png'),
  client_free_logo_lg: require('../assets/images/clients/clients_logos/free-range@3x.png'),

  client_asili_img_full_sm: require('../assets/images/clients/clients_pics/full/asili.jpg'),
  client_asili_img_full_md: require('../assets/images/clients/clients_pics/full/asili@2x.jpg'),
  client_asili_img_full_lg: require('../assets/images/clients/clients_pics/full/asili@3x.jpg'),
  client_asili_img_cropped_sm: require('../assets/images/clients/clients_pics/cropped/asili.jpg'),
  client_asili_img_cropped_md: require('../assets/images/clients/clients_pics/cropped/asili@2x.jpg'),
  client_asili_img_cropped_lg: require('../assets/images/clients/clients_pics/cropped/asili@3x.jpg'),
  client_asili_logo_sm: require('../assets/images/clients/clients_logos/asili.png'),
  client_asili_logo_md: require('../assets/images/clients/clients_logos/asili@2x.png'),
  client_asili_logo_lg: require('../assets/images/clients/clients_logos/asili@3x.png'),

  contact_map_sm: require('../assets/images/contact/contact-map.jpg'),
  contact_map_md: require('../assets/images/contact/contact-map@2x.jpg'),
  contact_map_lg: require('../assets/images/contact/contact-map@3x.jpg'),

  header_textless_logo: require('../assets/images/icons/logo-header.svg'),
  header_text_logo: require('../assets/images/icons/logo-and-text.svg'),
  nav_logo: require('../assets/images/icons/nav_logo.png'),

  footer_map_sm: require('../assets/images/footer/footer_map.jpg'),
  footer_map_md: require('../assets/images/footer/footer_map@2x.jpg'),
  footer_map_lg: require('../assets/images/footer/footer_map@3x.jpg'),

  home_banner_sm: require('../assets/images/services/services_banner-mobile.png'),
  home_banner_md: require('../assets/images/services/services_banner-tablet.png'),
  home_banner_lg: require('../assets/images/services/services_banner-desktop.png'),

  home_awards_bg_sm: require('../assets/images/home/home_awards_bg-mobile.png'),
  home_awards_bg_md: require('../assets/images/home/home_awards_bg-tablet.png'),
  home_awards_bg_lg: require('../assets/images/home/home_awards_bg-desktop.png'),

  press_herald_sm: require('../assets/images/home/press/herald.png'),
  press_herald_md: require('../assets/images/home/press/herald@2x.png'),
  press_herald_lg: require('../assets/images/home/press/herald@3x.png'),

  press_bizedge_sm: require('../assets/images/home/press/bizedge.png'),
  press_bizedge_md: require('../assets/images/home/press/bizedge@2x.png'),
  press_bizedge_lg: require('../assets/images/home/press/bizedge@3x.png'),

  press_nz_business_sm: require('../assets/images/home/press/nzbusiness.png'),
  press_nz_business_md: require('../assets/images/home/press/nzbusiness@2x.png'),
  press_nz_business_lg: require('../assets/images/home/press/nzbusiness@3x.png'),

  press_review_sm: require('../assets/images/home/press/the-national-business-review-logo.png'),
  press_review_md: require('../assets/images/home/press/the-national-business-review-logo@2x.png'),
  press_review_lg: require('../assets/images/home/press/the-national-business-review-logo@3x.png'),

  press_stuff_sm: require('../assets/images/home/press/stuff-logo.png'),
  press_stuff_md: require('../assets/images/home/press/stuff-logo@2x.png'),
  press_stuff_lg: require('../assets/images/home/press/stuff-logo@3x.png'),

  home_workshop_bg_sm: require('../assets/images/home/home_workshops_bg-mobile.jpg'),
  home_workshop_bg_md: require('../assets/images/home/home_workshops_bg-tablet.jpg'),
  home_workshop_bg_lg: require('../assets/images/home/home_workshops_bg-desktop.jpg'),

  home_slider_benefits_1_sm: require('../assets/images/home/slider/banner_1-mobile.jpg'),
  home_slider_benefits_1_md: require('../assets/images/home/slider/banner_1-tablet.jpg'),
  home_slider_benefits_1_lg: require('../assets/images/home/slider/banner_1-desktop.jpg'),
  home_slider_benefits_2_sm: require('../assets/images/home/slider/banner_2-mobile.jpg'),
  home_slider_benefits_2_md: require('../assets/images/home/slider/banner_2-tablet.jpg'),
  home_slider_benefits_2_lg: require('../assets/images/home/slider/banner_2-desktop.jpg'),
  home_slider_benefits_3_sm: require('../assets/images/home/slider/banner_3-mobile.jpg'),
  home_slider_benefits_3_md: require('../assets/images/home/slider/banner_3-tablet.jpg'),
  home_slider_benefits_3_lg: require('../assets/images/home/slider/banner_3-desktop.jpg'),
  home_slider_benefits_4_sm: require('../assets/images/home/slider/banner_4-mobile.jpg'),
  home_slider_benefits_4_md: require('../assets/images/home/slider/banner_4-tablet.jpg'),
  home_slider_benefits_4_lg: require('../assets/images/home/slider/banner_4-desktop.jpg'),
  home_slider_benefits_5_sm: require('../assets/images/home/slider/banner_5-mobile.jpg'),
  home_slider_benefits_5_md: require('../assets/images/home/slider/banner_5-tablet.jpg'),
  home_slider_benefits_5_lg: require('../assets/images/home/slider/banner_5-desktop.jpg'),

  home_awards_pic_sm: require('../assets/images/home/home_award.png'),
  home_awards_pic_md: require('../assets/images/home/home_award@2x.png'),
  home_awards_pic_lg: require('../assets/images/home/home_award@3x.png'),

  home_profile_img_head_sm: require('../assets/images/home/home_toss_profile.jpg'),
  home_profile_img_head_md: require('../assets/images/home/home_toss_profile@2x.jpg'),
  home_profile_img_head_lg: require('../assets/images/home/home_toss_profile@3x.jpg'),

  signature_img_sm: require('../assets/images/home/signature.svg'),

  footer_wolf_icon_sm: require('../assets/images/icons/logo-footer-small.png'),
  footer_wolf_icon_md: require('../assets/images/icons/logo-footer-small@2x.png'),
  footer_wolf_icon_lg: require('../assets/images/icons/logo-footer-small@3x.png'),
  footer_logo_sm: require('../assets/images/footer/footer_logo.png'),
  footer_logo_md: require('../assets/images/footer/footer_logo@2x.png'),
  footer_logo_lg: require('../assets/images/footer/footer_logo@3x.png'),

  services_banner_sm: require('../assets/images/services/services_banner-mobile.png'),
  services_banner_md: require('../assets/images/services/services_banner-tablet.png'),
  services_banner_lg: require('../assets/images/services/services_banner-desktop.png'),

  services_schedules_bg_sm: require('../assets/images/services/services_schedule_bg-mobile.png'),
  services_schedules_bg_md: require('../assets/images/services/services_schedule_bg-desktop.png'),
  services_schedules_bg_lg: require('../assets/images/services/services_schedule_bg-desktop.png'),

  services_grant_logo_sm: require('../assets/images/services/services_grants_logo.png'),
  services_grant_logo_md: require('../assets/images/services/services_grants_logo@2x.png'),
  services_grant_logo_lg: require('../assets/images/services/services_grants_logo@3x.png'),

  services_results_pic_1_sm: require('../assets/images/services/services_results_pic-1.jpg'),
  services_results_pic_1_md: require('../assets/images/services/services_results_pic-1@2x.jpg'),
  services_results_pic_1_lg: require('../assets/images/services/services_results_pic-1@3x.jpg'),
  services_results_pic_2_sm: require('../assets/images/services/services_results_pic-2.jpg'),
  services_results_pic_2_md: require('../assets/images/services/services_results_pic-2@2x.jpg'),
  services_results_pic_2_lg: require('../assets/images/services/services_results_pic-2@3x.jpg'),
  services_results_pic_3_sm: require('../assets/images/services/services_results_pic-3.jpg'),
  services_results_pic_3_md: require('../assets/images/services/services_results_pic-3@2x.jpg'),
  services_results_pic_3_lg: require('../assets/images/services/services_results_pic-3@3x.jpg'),
  services_results_pic_4_sm: require('../assets/images/services/services_results_pic-4@3x.jpg'),
  services_results_pic_4_md: require('../assets/images/services/services_results_pic-4@3x.jpg'),
  services_results_pic_4_lg: require('../assets/images/services/services_results_pic-4@3x.jpg'),

  icon_location: require('../assets/images/icons/location_icon.svg'),
  icon_location_grey: require('../assets/images/icons/icon_location_grey.svg'),
  icon_email: require('../assets/images/icons/mail_icon.svg'),
  icon_email_grey: require('../assets/images/icons/icon_email_grey.svg'),
  icon_phone: require('../assets/images/icons/phone_logo.svg'),
  icon_phone_grey: require('../assets/images/icons/icon_phone_grey.svg'),
  icon_website_link: require('../assets/images/icons/websitelink_icon.png'),
  icon_hamburger: require('../assets/images/icons/icon_hamburger.svg'),
  icon_close: require('../assets/images/icons/icon_close.svg'),

  icon_message_sent: require('../assets/images/icons/icon_message_sent.svg'),
  icon_star: require('../assets/images/icons/star.svg'),
  icon_arrow_down: require('../assets/images/icons/arrow_down.svg'),
  icon_arrow_white: require('../assets/images/icons/arrow_down_white.svg'),
  icon_arrow_to: require('../assets/images/icons/arrow_to.svg'),
  icon_meet_us: require('../assets/images/icons/meet-us_icon.svg'),

  icon_navigation_line: require('../assets/images/icons/arrows-navigation-line.svg'),
  icon_navigation_arrow: require('../assets/images/icons/icon_slider_arrow.svg'),

  icon_social_fb: require('../assets/images/icons/facebook_logo.svg'),
  icon_social_fb_grey: require('../assets/images/icons/icon_facebook_grey.svg'),
  icon_social_google_plus: require('../assets/images/icons/G_logo.svg'),
  icon_social_google_plus_grey: require('../assets/images/icons/G_logo_grey.svg'),
  icon_social_linkedIn: require('../assets/images/icons/linked_in_logo.svg'),
  icon_social_linkedIn_grey: require('../assets/images/icons/icon_linkedin_grey.svg'),
  icon_apple: require('../assets/images/icons/icon_apple.svg'),
  icon_google: require('../assets/images/icons/icon_google_plus.svg'),

  glyphs_copyright_logo: require('../assets/images/icons/7glyphs-footer-logo.png'),

  icon_loader: require('../assets/images/icons/icon_loader.svg'),
  icon_map_marker_star_grey: require('../assets/images/icons/map-marker-star-icon_grey.svg'),
  icon_map_marker_star_yellow: require('../assets/images/icons/map-marker-star-icon_yellow.svg'),

  feature_business_planning_icon: require('../assets/images/home/icon-feature-business-planning.svg'),
  feature_strategic_planning_icon: require('../assets/images/home/icon-feature-strategic-planning.svg'),
  feature_problem_solving_icon: require('../assets/images/home/icon-feature-problem-solving.svg'),
  feature_marketing_strategy_icon: require('../assets/images/home/icon-feature-marketing-strategy.svg'),
  feature_capital_raising_icon: require('../assets/images/home/icon-feature-capital-raising.svg'),

  workshops_banner_bg_sm: require('../assets/images/workshops/workshops_banner-mobile.png'),
  workshops_banner_bg_md: require('../assets/images/workshops/workshops_banner-tablet.png'),
  workshops_banner_bg_lg: require('../assets/images/workshops/workshops_banner-desktop.png'),

  workshops_schedule_bg_sm: require('../assets/images/workshops/workshops_schedules_bg.jpg'),
  workshops_schedule_bg_md: require('../assets/images/workshops/workshops_schedules_bg@2x.jpg'),
  workshops_schedule_bg_lg: require('../assets/images/workshops/workshops_schedules_bg@3x.jpg'),

  workshops_author_review_1: require('../assets/images/workshops/workshops_reviews_1@3x.jpg'),
  workshops_author_review_2: require('../assets/images/workshops/workshops_reviews_2@3x.jpg'),
  workshops_author_review_3: require('../assets/images/workshops/workshops_reviews_3@3x.jpg'),

  workshops_galley_img_1_sm: require('../assets/images/workshops/workshops_gallery_1.jpg'),
  workshops_galley_img_1_md: require('../assets/images/workshops/workshops_gallery_1@2x.jpg'),
  workshops_galley_img_1_lg: require('../assets/images/workshops/workshops_gallery_1@3x.jpg'),
  workshops_galley_img_2_sm: require('../assets/images/workshops/workshops_gallery_2.jpg'),
  workshops_galley_img_2_md: require('../assets/images/workshops/workshops_gallery_2@2x.jpg'),
  workshops_galley_img_2_lg: require('../assets/images/workshops/workshops_gallery_2@3x.jpg'),
  workshops_galley_img_3_sm: require('../assets/images/workshops/workshops_gallery_3.jpg'),
  workshops_galley_img_3_md: require('../assets/images/workshops/workshops_gallery_3@2x.jpg'),
  workshops_galley_img_3_lg: require('../assets/images/workshops/workshops_gallery_3@3x.jpg'),
  workshops_galley_img_4_sm: require('../assets/images/workshops/workshops_gallery_4.jpg'),
  workshops_galley_img_4_md: require('../assets/images/workshops/workshops_gallery_4@2x.jpg'),
  workshops_galley_img_4_lg: require('../assets/images/workshops/workshops_gallery_4@3x.jpg'),
  workshops_galley_img_5_sm: require('../assets/images/workshops/workshops_gallery_5.jpg'),
  workshops_galley_img_5_md: require('../assets/images/workshops/workshops_gallery_5@2x.jpg'),
  workshops_galley_img_5_lg: require('../assets/images/workshops/workshops_gallery_5@3x.jpg'),
  workshops_galley_img_6_sm: require('../assets/images/workshops/workshops_gallery_6.jpg'),
  workshops_galley_img_6_md: require('../assets/images/workshops/workshops_gallery_6@2x.jpg'),
  workshops_galley_img_6_lg: require('../assets/images/workshops/workshops_gallery_6@3x.jpg'),

  pack_profile_img_sm: require('../assets/images/pack/pack_profile_photo.jpg'),
  pack_profile_img_md: require('../assets/images/pack/pack_profile_photo@2x.jpg'),
  pack_profile_img_lg: require('../assets/images/pack/pack_profile_photo@3x.jpg'),

  pack_paper_bg_sm: require('../assets/images/pack/pack_paper_bg.png'),
  pack_paper_bg_md: require('../assets/images/pack/pack_paper_bg@2x.png'),
  pack_paper_bg_lg: require('../assets/images/pack/pack_paper_bg@3x.png')
}
